import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter as Router } from 'react-router-dom';
import App from './App';
import { Provider } from './hooks';
import { defaultProviders } from '@connect2ic/core/providers';
import { Connect2ICProvider } from '@connect2ic/react';
import { canisterId } from '../declarations';
import { PlugWallet } from "@connect2ic/core/providers/plug-wallet"
import { AstroX } from "@connect2ic/core/providers/astrox"
import { idlFactory } from '../declarations/superheroes.did.js';

// Styles for the ConnectDialog & Button
const providers = [
	// Either import them from @connect2ic/core
	AstroX,
	PlugWallet,
];

// Map of canister definitions as generated by dfx
// It requires the canisterId & idlFactory
const canisterDefinitions = {
	superheroes: { idlFactory, canisterId },
};
const host = window.location.origin;
ReactDOM.render(
	<Router>
		<Connect2ICProvider
			canisters={canisterDefinitions}
			providers={providers}
			
			host={host}
			autoConnect={true}>
			<Provider>
				<App />
			</Provider>
		</Connect2ICProvider>
	</Router>,
	document.getElementById('app')
);
