import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter as Router } from 'react-router-dom';
import App from './App';
import { Provider } from './hooks';
import { defaultProviders } from '@connect2ic/core/providers';
import { Connect2ICProvider } from '@connect2ic/react';
import { superheroes } from '../declarations';
import { idlFactory, canisterId } from '../declarations';

// Styles for the ConnectDialog & Button
const providers = [
	// Either import them from @connect2ic/core
	
];

// Map of canister definitions as generated by dfx
// It requires the canisterId & idlFactory
const canisterDefinitions = {
	superheroes : {idlFactory, canisterId}
};
const host = window.location.origin
ReactDOM.render(
	<Router>
		<Connect2ICProvider
			canisters={canisterDefinitions}
			providers={defaultProviders}
			dev={window.location.origin.includes("localhost")}
			host={host}>
			<Provider>
				<App />
			</Provider>
		</Connect2ICProvider>
	</Router>,
	document.getElementById('app')
);
