import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter as Router } from 'react-router-dom';
import App from './App';
import { Provider } from './hooks';
import { defaultProviders } from '@connect2ic/core/providers';
import { Connect2ICProvider } from '@connect2ic/react';
// Styles for the ConnectDialog & Button
const providers = [
	// Either import them from @connect2ic/core
	
];

// Map of canister definitions as generated by dfx
// It requires the canisterId & idlFactory
const canisterDefinitions = {
};
ReactDOM.render(
	<Router>
		<Connect2ICProvider
			canisters={canisterDefinitions}
			providers={defaultProviders}>
			<Provider>
				<App />
			</Provider>
		</Connect2ICProvider>
	</Router>,
	document.getElementById('app')
);
